### ISSUE TITLE
"Implicit" generators

### ISSUE THREAD

**Issue by eproxus** [dazuma/erl2ex#1]
Regarding the following known issue:
-   Erlang comprehensions seem to support "implicit" generators where Elixir doesn't. (Example in function `maybe_waiters/5` in https://github.com/uwiger/gproc/blob/master/src/gproc_lib.erl)

It might be considered an "implicit" generator, but the end effect is like an if statement that always returns a list. It is used more as a boolean check:

``` erl
1> L = [1,2,3].
[1,2,3]
2> [V || L =/= []].
* 1: variable 'V' is unbound
3> [a || L =/= []].
[a]
4> [a || L == []].
[]
5> [x || false].
[]
6> [x || true].
[x]
```

Perhaps it can be translated to `if L != [], do: [a], else: []`?

**Comment by dazuma** [comment]
Thanks for the tip. It looks like, as a generalization, Erlang allows qualifiers in any order, whereas Elixir requires that the _first_ qualifier be a generator. I used your "if" statement idea to handle leading non-generator qualifiers.

**Comment by eproxus** [comment]
Glad to be of help. :smile:
